### PR TITLE
Add conclusion part for the final report

### PR DESCRIPTION
**Pull request by jinyz8888**
@tonyshumlh @JohnShiuMK @SoloSynth1 Please review it.

### CODE REVIEW

**Comment by tonyshumlh** [comment]
@jinyz8888 I think we can merge all the changes to branch `add_final_report_doc` first before merging into `main`

**Comment by tonyshumlh** [comment]
Changes merged in branch `add_final_report_doc` https://github.com/UBC-MDS/fixml/pull/172

**Comment by jinyz8888** [comment]
@tonyshumlh yes, agree. Thanks!

**Comment by jinyz8888** [comment]
Merged into https://github.com/UBC-MDS/fixml/pull/94

**Pull request closed without merging**
